# Generated by Django 2.0 on 2018-03-24 23:11

import apiApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_auto_20180324_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.FileField(upload_to=apiApp.models.course_data_location)),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apiApp.Course')),
            ],
        ),
    ]
